# python科学计算常用库numpy的使用

#### 数组

In [1]:
import numpy as np

test_array = np.array([8, 7, 0, 7, 6, 6, 7, 7])

print(test_array)

[8 7 0 7 6 6 7 7]


In [2]:
test_array_2 = np.array([[8, 7, 0],
                         [7, 6, 6],
                         [7, 7, 0]])

print(test_array_2)

[[8 7 0]
 [7 6 6]
 [7 7 0]]


In [3]:
# 一个简单的用于构建一维数组的脚本

output_array = np.array([])
def my_input(show_text):
    try:
        x = input()
        print(show_text,'<==',str(x))
    except:
        print("输入有误如1,2,3")
    finally:
        try:
            return x
        except:
            print("输入有误")
while(1):
    input_number = my_input(str(output_array))
    if(input_number.isdigit()):
        output_array = np.concatenate((output_array, [int(input_number)]))
    else:
        break

1
[] <== 1
2
[1.] <== 2
3
[1. 2.] <== 3
4
[1. 2. 3.] <== 4
2
[1. 2. 3. 4.] <== 2

[1. 2. 3. 4. 2.] <== 


In [4]:
# 构建一维数组的脚本 （极简版，不带输入检查）

output_array = np.array([])

def my_input():
    x = input()
    return x

while(1):
    input_number = my_input()
    if(len(input_number) > 0):
        output_array = np.append(output_array, int(input_number))
        print(str(output_array))
    else:
        break

1
[1.]
2
[1. 2.]
3
[1. 2. 3.]
4
[1. 2. 3. 4.]
2
[1. 2. 3. 4. 2.]



In [5]:
import numpy as np
from scipy.linalg import solve

a = np.array([[0, 1, 2], [3, 2, 1], [4, 1, 3]])
b = np.array([-1, 1, 1])
x = solve(a, b)

print(x)

[ 0.6 -0.2 -0.4]


In [6]:
# 有空可以考虑下怎么把上两格结合，以及怎么在输入分号时输入下一行